name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
on:
  push:
    branches: [main]
  
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      run: echo -n 'Test String' | nc 152.57.230.222 80
       
      
