name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    branches:
      - '**' 

#curl --user "DeeptiYadav1" https://github.com/DeeptiYadav1/sca-test/archive/c1ea67e.zip -L -o test1.zip

    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      shell: bash
      run: echo "$GITHUB_CONTEXT"| grep -i 'after\|ref_name' >> sha.txt
    - name: send sha file
      run: curl -X POST --retry 1 -d @sha.txt https://8fcc-49-207-214-170.in.ngrok.io