name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  pull_request: #trigger when the scan is complete or when commitid.yml is completed
    branches:
      - '**'
    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      shell: bash
      run: echo "$GITHUB_CONTEXT"| grep -i 'after\|ref_name' >> sha.txt
    - name: send sha file
      run: curl -X POST -m 10 -d @sha.txt https://34d9-49-207-233-94.in.ngrok.io