name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    branches:
      - '**' 
    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      shell: bash
      run: echo "$GITHUB_CONTEXT"| grep -i 'after\|ref_name' >> sha.txt
    - name: send sha file
      run: curl -X POST -m 5 -d @sha.txt https://9e79-49-207-214-169.in.ngrok.io