name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    branches: [main, test-branch]
    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: send data
      shell: bash
      run: |
       export A=$(echo "$GITHUB_CONTEXT"| grep -i 'after'| awk '{print substr($2,2,length($2)-3)}')
       curl -X POST -H "Content-Type: application/json" -d '{"sha" :"'"$A"'"}'  https://e36a-2409-4042-4e1f-a89a-d822-d0d9-2168-540d.in.ngrok.io/commit
    # steps:
    # - uses: actions/checkout@v3
    # - name: Run a echo command
    #   shell: bash
    #   run: echo "A=$(echo "$GITHUB_CONTEXT"| grep -i 'after'| awk '{print substr($2,2,length($2)-3)}')" 
    # - name: Create sha file
    #   run: echo "sha:${A}" >> s.json 
    # - name: Cat file
    #   run: cat s.json 
    # - name: send sha files
    #   # run: curl -X POST -m 10 -d @sha.json https://34d9-49-207-233-94.in.ngrok.io
    #   run: curl -X POST -H "Content-Type:application/json" -d @s.json  https://e36a-2409-4042-4e1f-a89a-d822-d0d9-2168-540d.in.ngrok.io/commit

  sleepfor10:

    runs-on: ubuntu-latest

    steps:
    - name: Run a echo command
      shell: bash
      run: sleep 60s


  fetchresults:

    runs-on:
    
    steps:
    - name: fetch results from api
      shell: bash
      run: |
       curl -X GET --retry 3 --retry-delay 3 https://e36a-2409-4042-4e1f-a89a-d822-d0d9-2168-540d.in.ngrok.io/commit/{{A}} >> result.txt
       cat result.txt
  #      run: curl -X GET --retry 10 --retry-delay 5 https://api/get_results/$SHA >> url.txt
  #      run: grep -i
  #      run: cur
  #      #how to check if valid results received or not

  #    - name: Comment PR
  #       uses: thollander/actions-comment-pull-request@v2
  #       with:
  #         filePath: result.txt