name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    branches: [main, test-branch]
    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      shell: bash
      run: echo "A=$(echo "$GITHUB_CONTEXT"| grep -i 'after'| awk '{print substr($2,2,length($2)-3)}')" 
      run: echo "sha:${A}" >> s.json
    - name: send sha files
      # run: curl -X POST -m 10 -d @sha.json https://34d9-49-207-233-94.in.ngrok.io
      run: curl -X POST -H "Content-Type:application/json" -d @s.json  https://c2bd-2409-4042-4e1f-a89a-2123-daf1-9cc0-2735.in.ngrok.io/commit

  # sleepfor10:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Run a echo command
  #     shell: bash
  #     run: sleep 300


  # fetchdetails: #api creation

  #   runs-on:
    
  #   steps:
  #    - name: fetch results from api
  #      run: curl -X GET --retry 10 --retry-delay 5 https://api/get_results/$SHA >> url.txt
  #      run: grep -i
  #      run: cur
  #      #how to check if valid results received or not

  #    - name: Comment PR
  #       uses: thollander/actions-comment-pull-request@v2
  #       with:
  #         filePath: result.txt