name: Send Branch name and Commit Id
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
on:
  push:
    branches: [main, test-branch]

    
jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a echo command
      shell: bash
      run: |
          
          echo "Hi test"
       
