name: Send Results to PR
on:
  schedule:
    - cron: '5 * * * *' 

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GET Results
        run: |
            curl -X GET "https://9a7f-49-207-231-26.in.ngrok.io/test.txt" -o result.txt

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: result.txt
            