name: Send Results to PR
on:
  repository_dispatch:
    types: [test_result]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: GET Results
      #   run: |
      #       curl --retry 10 --retry-delay 5 -f --retry-all-errors -X GET 'https://a114-49-207-209-105.in.ngrok.io/test.txt' -o result.txt

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: Hello
            