name: Send Results to PR
on:
  pull_request:
    branches: [main]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 
            curl -X GET "https://fbb2-49-207-226-44.in.ngrok.io/test.txt"
            