name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: test

jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo "Hi"