name: Rerun Action
on:
  workflow_call:
    inputs:
      sha-value:
        required: true
        type: string



jobs:
  senddetails:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: send data
      shell: bash
      run: echo ${{sha-value}}

# jobs:
#   call-commitid:
#     uses: DeeptiYadav1/sca-test/blob/test-branch/.github/workflows/commitid.yml
    