name: Do Something That Needs Scheduled

on:
  workflow_dispatch:
    inputs:
      shavalue:
        description: 'sha-value'
        required: true
        type: string
      prnumber:
        description: 'pr-number'
        required: true
        type: int

  

jobs:

  # senddetails:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: send data
  #     shell: bash
  #     env:
  #         SHA: ${{ inputs.shavalue }}
  #     run: |
  #      curl -X POST -H "Content-Type: application/json" -d '{"sha" :"'"$SHA"'"}'  https://39ab-2409-4042-4e17-ebad-4d82-595c-7437-ad68.in.ngrok.io/commit


  fetchresults:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: fetch results from api
      shell: bash
      env:
          SHA: ${{ inputs.shavalue }}
      run: |
       sleep 5s
       curl -X GET --retry 10 --retry-delay 5 'https://16d7-2409-4042-4e17-ebad-a405-b8a8-29ff-3aff.in.ngrok.io/commit/'"${SHA}" >> result.txt
       cat result.txt
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: result.txt
        pr_number: ${{ inputs.prnumber }}
        




    