name: Do Something That Needs Scheduled

on:
  workflow_dispatch:
    inputs:
      shavalue:
        description: 'sha-value'
        required: true
        type: string
  

jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SHA Value: $SHA"
        env:
          SHA: ${{ inputs.shavalue }}
          



# jobs:
#   call-commitid:
#     uses: DeeptiYadav1/sca-test/blob/test-branch/.github/workflows/commitid.yml
    