name: Do Something That Needs Scheduled

on:
  workflow_dispatch:
  

jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo "Hello"




# jobs:
#   call-commitid:
#     uses: DeeptiYadav1/sca-test/blob/test-branch/.github/workflows/commitid.yml
    